# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Lived Experiences — Race at Miami
email: livedexperiences@miamioh.edu
description: >- # this means to ignore newlines until "baseurl:"
  Race at Miami University is a collaborative storytelling project that chronicles the history of racial dynamics
  at Miami University through documentaries, oral histories, and archival stories of students, alumni, faculty,
  and staff of color. At the heart of the project are the lived experiences of the past and present who have 
  shared their experiences while providing resources for teaching, studying and learning.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://livedmu.lib.miamioh.edu' # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: G-KPG76EL79B

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#

minima:
  social_links:
    - { platform: instagram, user_url: 'https://www.instagram.com/MiamiOHLib' }
    - { platform: twitter, user_url: 'https://twitter.com/MiamiOHLib' }
    - { platform: facebook, user_url: 'https://www.facebook.com/MiamiOHLib' }
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - studio/

collections:
  stories:
    output: true
  trailblazers:
    output: true
