on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:Miamiohlibs/raceatmiami.git"
          source_branch: "develop"
          destination_repo: "git@github.com:raceatmiami/raceatmiami.github.io.git"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
